n1 = input('Digite algo: ')
print('O tipo primitivo é', type(n1))
print('É um número?', n1.isnumeric())
print('É alfabético?',  n1.isalpha())
print('Tem somente espaços?', n1.isspace())
print('É alfanumérico?', n1.isalnum())
print('Tem maiúsculos?', n1.isupper())
print('Tm minúsculos?', n1.islower()) 
print('Está capitalisada?', n1.istitle())
